# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 03 Dec 2017 10:10:24 +0000
*               @ALL          1
*               @user         8
