<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sun, 03 Dec 2017 11:18:45 +0000
 */

$conf['title'] = 'Project docs';
$conf['template'] = 'writr';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['gzip_output'] = 1;

// end auto-generated content
