FROM alpine:latest

RUN apk add --update \
    php7-fpm \
    php7-gd \
    php7-dom \
    php7-json \
    php7-mbstring \
    php7-session \
    php7-ctype \
    php7-curl \
    php7-xml \
    php7-openssl \
    php7-zip \
    php7-zlib

RUN sed -i -e 's/127\.0\.0\.1/0\.0\.0\.0/' /etc/php7/php-fpm.d/www.conf

EXPOSE 9000

CMD ["/usr/sbin/php-fpm7", "--nodaemonize"]