version: "3"
services:
    web:
        image: nginx:alpine
        ports:
            - 80:80
        links:
            - php
        volumes:
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html/
        restart: always

    php:
        build: 
            context: .
            dockerfile: Dockerfile.fpm
        ports:
            - 9000
        volumes:
            - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./:/var/www/html/
            - /var/www/html
        restart: always
